### ISSUE TITLE
1.0 Milestones

### ISSUE THREAD

**Issue by HagaiHargil** [HagaiHargil/python-pysight#13]
- [x] Support binary list files.
- [ ] Multiprocessing.
- [ ] Demultiplex more than one coordinate signal per channel.
- [x] Simplify `Movie()` by grabbing the raw signals from `dict_of_data` and using the row indices of the `DataFrame` as the data points - not the `abs_time` column.
- [ ] Refactor `SignalValidator` - remove `CORRUPT` option and clarify API to the `mscan` and `scanimage` modules.
